services:
  client:
    image: node:20-alpine3.20
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm i && npm run dev"
    ports:
    - "8081:8081"
    depends_on:
      - refiner-service
  refiner-service:
    image: python:3.13-slim
    platform: linux/amd64
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    working_dir: /app
    volumes:
      - ./refiner:/app
    ports:
      - "8080:8080"
    extra_hosts:
        - "localhost:host-gateway"
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - DB_URL=postgresql://postgres:refiner@db:5432/refiner
      - AUTH_PROVIDER=keycloak
      - AUTH_CLIENT_ID=refinerclient
      - AUTH_CLIENT_SECRET=5yXLmlYFPYeQh4HOsO1MvqaLHlVj5aKv
      - AUTH_ISSUER=http://localhost:8082/realms/refiner
    logging:
      driver: "json-file"
    depends_on:
      - db
      - auth
  auth:
    image: quay.io/keycloak/keycloak:26.3.1
    command:
      - "start-dev"
      - "--import-realm"
      - "--http-port=8082"
      - "--hostname-strict=false"
    ports:
      - "8082:8082"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
    volumes:
      - ./keycloak/exports:/opt/keycloak/data/import
  db:
    image: postgres:alpine
    restart: on-failure
    user: postgres
    environment:
      - POSTGRES_DB=refiner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=refiner
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./refiner/tests/integration/seeding/seed-data.sql:/docker-entrypoint-initdb.d/seed-data.sql
      - ./refiner/app/db:/app/db
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
